#pragma once

#define CODELET_DEV_FALLBACK_WIFI_SSID "your-wifi-ssid"
#define CODELET_DEV_FALLBACK_WIFI_PASSWORD "your-wifi-password"
#define CODELET_DEV_FALLBACK_AGENT_HOST "192.168.1.23"
#define CODELET_DEV_FALLBACK_AGENT_PORT 8765
#define CODELET_DEV_FALLBACK_API_TOKEN ""
